name: devenv-vu-hgq+da
dependencies:
  - tensorflow
  - numpy
  - notebook
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - hgq2
      - "hls4ml[profiling, hgq2, da] @ git+https://github.com/lolbraa/hls4ml-kv260.git@VitisUnifiedClean"
#    - hls4ml[profiling,hgq2,da]
