# syntax=docker/dockerfile:1

# Credit for inspiration goes to 
# FastMachineLearning (https://github.com/fastmachinelearning/hls4ml-tutorial/blob/docker_build/docker/)
# ESnet (https://github.com/esnet/xilinx-tools-docker/blob/main/Dockerfile)
# filmil (https://github.com/filmil/vivado-docker/blob/main/docker/Dockerfile)
# cmu-sei (https://github.com/cmu-sei/hls4ml-docker/blob/main/Dockerfile)
# If deviating from the default paths, please make sure the entrypoint.sh matches

FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

# Use bash
SHELL ["/bin/bash", "-c"]

###### Declaring variables for building if you need to change something up
# Version of Vivado/Vitis which is downloaded
ENV TOOL_VERSION=2025.2

# Paths on the host machine for importing the files into the image
# Notice: Using the Web Installer to download only which modules you need, ends in a zip. 
# However, downloading the complete unified installer from website ends up with a .tar 
# (https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vivado-design-tools.html)
ARG HOST_TOOL_INSTALLER_ARCHIVE="./installer/xilinx_2025.2_Vitis.zip" 
#ARG HOST_TOOL_INSTALLER_ARCHIVE="./installer/FPGAs_AdaptiveSoCs_Unified_SDI_${TOOL_VERSION}_1114_2157_1.tar"
ARG HOST_TOOL_INSTALLER_CONFIG="./installer/install_config_vitis_2025.2.txt"

# Where Vivado/Vitis files are installed
ARG TOOL_INSTALLER_ARCHIVE="/tmp/installer/archive.zip"
ARG TOOL_INSTALLER_CONFIG="/tmp/installer/install_config.txt"
ARG TOOL_TARGET_INSTALL_PATH="/opt/Xilinx"

# Misc
ARG CONDA_PATH="/opt/miniconda3"
ARG CODE_RELEASE
ARG CODE_PATH="/opt/code-server"


######## Install dependencies and cache
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \ 
    && apt-get update &&  apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
    # Packages required for running the installer and Vitis
      ca-certificates \
      locales \
      lsb-release \
      net-tools \
      patch \
      wget \
    # From installLibs.sh:
      ### AIE Tools prerequisite libraries
      libc6-dev-i386 net-tools \
      graphviz \
      make \
      ### Vitis Tools prerequisite libraries
      unzip \
      zip \
      g++ \
      xvfb \
      # https://adaptivesupport.amd.com/s/article/76616?language=en_US
      libtinfo5 \
      libncurses5 \
      libncurses5-dev \
      libc6-dev-i386 \
      libnss3-dev \
      libgdk-pixbuf2.0-dev \
      libgtk-3-dev \
      libxss-dev  \
      #libasound2   \
      #compat-openssl10  \
      openssl \
      fdisk  \
      libsecret-1-dev \
    # VS Code server dependencies
      libatomic1 \
    # Custom environment
      curl \
      python3 \
      python3-pip \
      git \
      nano \
      vim \
    && apt-get autoclean \
    && apt-get autoremove \
  # && Vivado needs locale EN_us
    && locale-gen en_US.UTF-8 \
    && update-locale LANG=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*


##### Vivado/Vitis installation
# Import config file for installation
COPY $HOST_TOOL_INSTALLER_CONFIG $TOOL_INSTALLER_CONFIG
# Bind mounts the ./installer-directory under building so they are not redundantly 
# copied into the containers filesystem from the build context.
# You may want to skip importing and extracting an archive, and instead mount the extracted folder.
# I've chosen to do it like this for maximum compatibility with e.g. the downloadable complete unified installer archive 
# Install Vitis and Vivado. 
# https://docs.amd.com/r/en-US/ug973-vivado-release-notes-install-license
RUN --mount=type=bind,source=${HOST_TOOL_INSTALLER_ARCHIVE},target=${TOOL_INSTALLER_ARCHIVE} \
    echo "Extracting archive (this takes quite a while)..." \
    && mkdir -p /tmp/installer-extract \
    && unzip -q ${TOOL_INSTALLER_ARCHIVE} -d /tmp/installer-extract \
    #&& tar -xf ${TOOL_INSTALLER_ARCHIVE} -C /tmp/installer-extract # .tar installation archive
    && echo "Running xsetup batch install..." \
    && cd "/tmp/installer-extract/" \
#    && cd "/tmp/installer-extract/$(ls /tmp/installer-extract)" \ # .tar installation archive
    && ./xsetup \
      --batch Install \
      --location ${TOOL_TARGET_INSTALL_PATH} \
      --config ${TOOL_INSTALLER_CONFIG} \
      --agree XilinxEULA,3rdPartyEULA \
    && echo "Cleaning up extracted archive..." \
    && rm -rf /tmp/installer-extract/

# Check dependencies missing for running Vivado and Vitis
# This' the official method, however, we extracted the packages and installed them initially
#RUN bash ${TOOL_TARGET_INSTALL_PATH}/${TOOL_VERSION}/Vitis/scripts/installLibs.sh \
#	  && bash ${TOOL_TARGET_INSTALL_PATH}/${TOOL_VERSION}/Vivado/scripts/installLibs.sh

#### VS Code server
# Uses this for interacting and dynamically change Python-kernel through browser or VS Code client.
# Installs and configures appropriately
RUN  if [ -z ${CODE_RELEASE+x} ]; then \
    CODE_RELEASE=$(curl -sX GET https://api.github.com/repos/coder/code-server/releases/latest \
      | awk '/tag_name/{print $4;exit}' FS='[""]' | sed 's|^v||'); \
    fi \
    && mkdir -p ${CODE_PATH} \
    && curl -o /tmp/code-server.tar.gz -L \
      "https://github.com/coder/code-server/releases/download/v${CODE_RELEASE}/code-server-${CODE_RELEASE}-linux-amd64.tar.gz" \
    && tar xf /tmp/code-server.tar.gz -C \
      ${CODE_PATH} --strip-components=1 \
    && rm -rf \
      /tmp/* \
      /var/tmp/*
RUN ${CODE_PATH}/bin/code-server --install-extension ms-python.python \
    #&& ${CODE_PATH}/bin/code-server --install-extension ms-python.vscode-pylance \
    && ${CODE_PATH}/bin/code-server --install-extension ms-toolsai.jupyter \
    #|| true # VS Code failed to retrieve because of server error, this will try but keep going if it is down
    && mkdir -p /root/.local/share/code-server/User \
    && echo '{"python.defaultInterpreterPath": "/opt/miniconda3/bin/python"}' > /root/.local/share/code-server/User/settings.json
EXPOSE 8443


##### Setting up environments for running HLS4ML
# Installing and configuring dependencies
RUN curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o Miniconda3-latest-Linux-x86_64.sh \
    && bash Miniconda3-latest-Linux-x86_64.sh -b -p ${CONDA_PATH} \
    && rm Miniconda3-latest-Linux-x86_64.sh \
# Chose to not install jupyter by default. User may choose to install through their own environment
#    && ${CONDA_PATH}/bin/pip install jupyter notebook ipykernel \
    && source ${CONDA_PATH}/etc/profile.d/conda.sh \
    && conda init --all \
    && conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main \
    && conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r \
    # When trying Ubuntu 24.04 Conda filed solving environment if it hadn't updated, weird
    && conda update conda
# Expose 8888 for Jupyter notebook default
EXPOSE 8888
RUN mkdir /work

# Notice: two following sections are commented out to save space on the shipped image.
# Environments may easily be set up at runtime, see README.

# Setting up HLS4ML-tutorial at buildtime - may be commented out
#RUN source ${CONDA_PATH}/etc/profile.d/conda.sh \
#    && conda init bash \
#    && cd /work \
#    && git clone https://github.com/fastmachinelearning/hls4ml-tutorial/ \
#    && cd hls4ml-tutorial/ \
#    && conda env create -f environment.yml \
#    && conda run -n hls4ml-tutorial pip install ipykernel \
#    && conda run -n hls4ml-tutorial python -m ipykernel install --user --name hls4ml-tutorial --display-name "hls4ml-tutorial"

# Setting up custom environments at buildtime by importing from ./environments/.
# Uses conda to install and make ipykernels available
#COPY /environments/environment-*.yml /work/environments/
#WORKDIR /work
#RUN source ${CONDA_PATH}/etc/profile.d/conda.sh \
#    && for envfile in /work/environments/environment-*.yml; do \
#        if [ -f "$envfile" ]; then \
#           envname=$(basename "$envfile" .yml | sed 's/environment-//'); \
#           echo "Creating environment: $envname"; \
#           conda env create -f "$envfile" || true; \
#           conda run -n "$envname" pip install ipykernel || true; \
#           conda run -n "$envname" python -m ipykernel install --user --name "$envname" --display-name "$envname" || true; \
#        fi
#    done 

# Entrypoint sources Vivado/Vitis and boots into VS Code.
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]